# COCO implementation test

This notebook is an implementation of the constrained covariance from [Kernel Constrained Covariance for Dependence Measurement, A.Gretton et al.,2005](https://proceedings.mlr.press/r5/gretton05a/gretton05a.pdf)

### Generating some random variables

In [1]:
import numpy as np

In [33]:
def X(n:int=None,cov: np.array=np.identity(3),mean: np.array = np.zeros(3))->np.array:
    """Args:
    n,int: number of samples by default n=None ie a single sample
    cov,np.array: covariance matrix by default cov=np.identity(3)
    mean: mean value vector by default mean=np.zeros(3)

    returns n samples of the 
    """
    return np.random.multivariate_normal(mean,cov,n)

In [34]:
print(X(n=3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-1.52069221 -0.93345618  1.30042786]
 [ 0.2681583  -0.53577086  1.86046811]
 [-0.41720719 -0.10443379 -0.1360053 ]]
